name: julia
env:
  JULIA_NUM_THREADS: 2
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.0
          - 1 # automatically expands to the latest stable 1.x release of Julia
          - nightly
        os:
          - ubuntu-latest
        arch:
          - x64
        #   - x86
        # include:
        #   # test macOS and Windows with latest Julia only
        #   - os: macOS-latest
        #     arch: x64
        #     version: 1
        #   - os: windows-latest
        #     arch: x64
        #     version: 1
        #   - os: windows-latest
        #     arch: x86
        #     version: 1
    steps:
      - name: Setup julia and clone the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: julia -e 'import Pkg; Pkg.add("Test"); Pkg.add("UnicodePlots")'
      - name: Test with in-line script
        run: |
          @show pwd()
        shell: julia {0}
      - name:  Test using "test/runtests.jl"
        # uses: julia-actions/julia-runtest@v1
        - run: julia -e 'include("test/runtests.jl")'
