name: julia
env:
  JULIA_NUM_THREADS: 2
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.0
          - 1 # automatically expands to the latest stable 1.x release of Julia
          - nightly
        os:
          - ubuntu-latest
        arch:
          - x64
        #   - x86
        # include:
        #   # test macOS and Windows with latest Julia only
        #   - os: macOS-latest
        #     arch: x64
        #     version: 1
        #   - os: windows-latest
        #     arch: x64
        #     version: 1
        #   - os: windows-latest
        #     arch: x86
        #     version: 1
    steps:
      - name: Setup julia and clone the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y tar; julia -e 'import Pkg; Pkg.add("LinearAlgebra"); Pkg.add("UnicodePlots"); Pkg.add("Distributed"); Pkg.add("ProgressMeter")'
      - name:  Test 1 iteration and plot
        run: julia -e 'include("test/test_CI.jl"); fun_sim_impute_check(P_missing_pools=0.5, P_missing_loci=0.5, n_int_number_of_iterations=1)'
      - name:  Test 10 iterations and assess accuracy
        run: julia -e 'include("test/test_CI.jl"); fun_sim_impute_check(P_missing_pools=0.1, P_missing_loci=0.1, n_int_number_of_iterations=10)'
